# Request-Response Configuration Demo
# Demonstrates negative repeat values for request-response patterns

Messages:
  # Send immediately, then wait for 1 client message before each subsequent send
  - file name: start\.1\.bin
    delay: 0
    repeat: -1          # Wait for 1 client message between sends
    waitCount: 0        # Start immediately
    
  # Send after 2nd client message, then wait for 2 client messages between sends  
  - file name: start\.2\.bin
    delay: 100
    repeat: -2          # Wait for 2 client messages between sends
    waitCount: 2        # Start after 2nd client message
    
  # Normal positive repeat for comparison
  - file name: start\.3\.bin
    delay: 0
    repeat: 3           # Send 3 times with no waiting
    waitCount: 1        # Send after 1st client message
