# Immediate mode configuration
# Sends files immediately upon client connection (waitCount = 0)

Messages:
  - file name: start\.1\.bin
    delay: 0
    repeat: 1
    waitCount: 0        # Send immediately
  - file name: graph\..*\.bin
    delay: 16
    repeat: 0           # 0 = infinite repeat
    waitCount: 0        # Send immediately
  - file name: numeric\..*\.bin
    delay: 50
    repeat: 0           # 0 = infinite repeat
    waitCount: 0        # Send immediately
